const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.EightDir,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.solid,
		C3.Behaviors.Anchor,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.JavaScriptInEvents.FolhaDeEventos4_Event4,
		C3.Plugins.System.Acts.SetLayoutSampling
	];
};
self.C3_JsPropNameTable = [
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{"8Direções2": 0},
	{carro1: 0},
	{Teclado: 0},
	{pare: 0},
	{faixas1: 0},
	{npc: 0},
	{fundo: 0},
	{Textopare: 0},
	{questão1A: 0},
	{Sólido: 0},
	{pareblock: 0},
	{Questão1B: 0},
	{rpcerta: 0},
	{rperrada: 0},
	{carronpc: 0},
	{sinalizaçãonpc: 0},
	{blockcarnpc: 0},
	{oQueFazer: 0},
	{CERTO2: 0},
	{ERRADO2: 0},
	{Questão2A: 0},
	{Questão2B: 0},
	{fundo2: 0},
	{blockcarroinv: 0},
	{blockparedes: 0},
	{placa30km: 0},
	{block30km: 0},
	{bt30kmA: 0},
	{bt30kmB: 0},
	{oqFazer30km: 0},
	{palcavireadireita: 0},
	{blockreg1: 0},
	{Btreg1A: 0},
	{Btreg1B: 0},
	{perguntareg1: 0},
	{Âncora: 0},
	{pontuaçãoC: 0},
	{acertos: 0},
	{Erros1: 0},
	{erronum: 0},
	{DESVIE: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Mouseinicio: 0},
	{btinicio: 0},
	{planodefundoinv: 0},
	{PlanoDeFundoEmBlocos: 0},
	{btntentarnovamente: 0},
	{sairbt: 0},
	{parabensvocepassou: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{jogarnovamente: 0},
	{sairparabens: 0},
	{Áudio: 0},
	{Navegador: 0},
	{pontuacaoC: 0},
	{erropontuacao: 0}
];

self.InstanceType = {
	carro1: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	pare: class extends self.ISpriteInstance {},
	faixas1: class extends self.ISpriteInstance {},
	npc: class extends self.ISpriteInstance {},
	fundo: class extends self.ITiledBackgroundInstance {},
	Textopare: class extends self.ITextInstance {},
	questão1A: class extends self.IButtonInstance {},
	pareblock: class extends self.ISpriteInstance {},
	Questão1B: class extends self.IButtonInstance {},
	rpcerta: class extends self.ITextInstance {},
	rperrada: class extends self.ITextInstance {},
	carronpc: class extends self.ISpriteInstance {},
	sinalizaçãonpc: class extends self.ISpriteInstance {},
	blockcarnpc: class extends self.ISpriteInstance {},
	oQueFazer: class extends self.ITextInstance {},
	CERTO2: class extends self.ITextInstance {},
	ERRADO2: class extends self.ITextInstance {},
	Questão2A: class extends self.IButtonInstance {},
	Questão2B: class extends self.IButtonInstance {},
	fundo2: class extends self.ITiledBackgroundInstance {},
	blockcarroinv: class extends self.ISpriteInstance {},
	blockparedes: class extends self.ISpriteInstance {},
	placa30km: class extends self.ISpriteInstance {},
	block30km: class extends self.ISpriteInstance {},
	bt30kmA: class extends self.IButtonInstance {},
	bt30kmB: class extends self.IButtonInstance {},
	oqFazer30km: class extends self.ITextInstance {},
	palcavireadireita: class extends self.ISpriteInstance {},
	blockreg1: class extends self.ISpriteInstance {},
	Btreg1A: class extends self.IButtonInstance {},
	Btreg1B: class extends self.IButtonInstance {},
	perguntareg1: class extends self.ITextInstance {},
	pontuaçãoC: class extends self.ITextInstance {},
	acertos: class extends self.ITextInstance {},
	Erros1: class extends self.ITextInstance {},
	erronum: class extends self.ITextInstance {},
	DESVIE: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Mouseinicio: class extends self.IInstance {},
	btinicio: class extends self.ISpriteInstance {},
	planodefundoinv: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	btntentarnovamente: class extends self.ISpriteInstance {},
	sairbt: class extends self.ISpriteInstance {},
	parabensvocepassou: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	jogarnovamente: class extends self.ISpriteInstance {},
	sairparabens: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Navegador: class extends self.IInstance {}
}